# Generated by Django 4.1 on 2023-01-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_documentpred_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentpred",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
