# Generated by Django 4.1 on 2023-01-13 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_excel_file_upload_train"),
    ]

    operations = [
        migrations.CreateModel(
            name="Model_training_Metrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("epochs_no", models.IntegerField()),
                ("loss", models.FloatField()),
                ("accuracy", models.FloatField()),
                (
                    "file_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.excel_file_upload_train",
                    ),
                ),
            ],
        ),
    ]
