# Generated by Django 4.1 on 2023-01-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_documentpred_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentpred",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
