# Generated by Django 4.1 on 2023-01-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_documentpred_done"),
    ]

    operations = [
        migrations.CreateModel(
            name="Excel_File_upload_train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset", models.FileField(upload_to="media/")),
                ("trained", models.BooleanField(default=False)),
                ("epochs", models.IntegerField()),
                ("test_split", models.IntegerField()),
            ],
        ),
    ]
